### ISSUE TITLE
AttributeError: module 'tensorflow.python.ops.nn' has no attribute 'rnn_cell'

### ISSUE THREAD

**Issue by shikha4444** [stanfordnlp/mac-network#5]
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
Traceback (most recent call last):
  File "main.py", line 23, in <module>
    from model import MACnet
  File "/home/gpuuser/shikha_phd/shikha/mac-network_figure_qa/model.py", line 6, in <module>
    import ops
  File "/home/gpuuser/shikha_phd/shikha/mac-network_figure_qa/ops.py", line 5, in <module>
    from mi_gru_cell import MiGRUCell
  File "/home/gpuuser/shikha_phd/shikha/mac-network_figure_qa/mi_gru_cell.py", line 4, in <module>
    class MiGRUCell(tf.nn.rnn_cell.RNNCell):
AttributeError: module 'tensorflow.python.ops.nn' has no attribute 'rnn_cell'

**Comment by mayankjobanputra** [comment]
@shikha4444 can you check your tensorflow version? 
TensorFlow changed a lot of APIs before 1.0.

Can you replace tf.nn.rnn_cell by tf.contrib.rnn and check?

**Comment by shikha4444** [comment]
I have replaced in all the file. This error  "AttributeError: module 'tensorflow.python.ops.nn' has no attribute 'rnn_cell'" got resolved but then after data processing got the below-mentioned error.


Building model...
Traceback (most recent call last):
  File "main.py", line 801, in <module>
    main()
  File "main.py", line 671, in main
    model = MACnet(embeddings, answerDict)
  File "/home/gpuuser/shikha_phd/shikha/mac-network_figure_qa/model.py", line 35, in __init__
    self.build()
  File "/home/gpuuser/shikha_phd/shikha/mac-network_figure_qa/model.py", line 788, in build
    self.questionLengths, projWords, projQuestion, config.ctrlDim)
  File "/home/gpuuser/shikha_phd/shikha/mac-network_figure_qa/model.py", line 294, in encoder
    dropout = self.dropouts["encInput"], varDp = varDp, name = "rnn%d" % i)
  File "/home/gpuuser/shikha_phd/shikha/mac-network_figure_qa/ops.py", line 952, in RNNLayer
    return rnn(inSeq, seqL, hDim, cellType = cellType, dropout = dropout, varDp = varDp) # , proj = proj
  File "/home/gpuuser/shikha_phd/shikha/mac-network_figure_qa/ops.py", line 866, in biRNNLayer
    cellFw = createCell(hDim, reuse, cellType)
  File "/home/gpuuser/shikha_phd/shikha/mac-network_figure_qa/ops.py", line 770, in createCell
    cell = cells[cellType](hDim, reuse = reuse, activation = activation)
TypeError: __init__() got an unexpected keyword argument 'reuse'

**Comment by mayankjobanputra** [comment]
Can you please specify the version of the Tensorflow that you are using?

**Comment by shikha4444** [comment]
1.0.1

**Comment by shikha4444** [comment]
Thanks for your help.

**Comment by shikha4444** [comment]
Now the code is running fine. But it is running on CPU, not on GPU.
